on:
  push # temporary, change to monthly after testing

name: Create Release

jobs:
  compile:
    name: Compile using DevkitPro
    runs-on: macos-latest
    steps:
      - name: Install custom pacman command
        run: |
         sudo installer -pkg devkitpro-pacman-installer.pkg -target /
         xcode-select --install
      - name: Use custom pacman to get the 3ds package
        run: sudo (dkp-)pacman -S 3ds-dev
      - name: Run Makefile to compile
        run: make
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          body: Automatically compiled from a w.i.p. workflow
          draft: true
          prerelease: true
          replacesArtifacts: true
  uploadbin:
    needs: [compile, build]
    name: Insert binary files to release
    runs-on: ubuntu-latest
    steps:
      - uses: tanyagray/action-upload-release-asset@v1.1.3
        with:
          upload_url: steps.create_release.outputs.upload_url
          asset_path: scratch-3ds.3dsx
          asset_name: scratch-3ds.3dsx
          asset_content_type: application/octet-stream
